from setuptools import setup

setup(
    name='mapography',
    version='0.1.0a0',
    description='Map file analyser',
    long_description='Parse and return informations on a map file generated by'
                     ' a software compiler',
    url='https://github.com/fparat/mapography',
    author='Franck Parat',
    author_email='franck.parat@gmail.com',
    license='MIT',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'Topic :: Software Development :: Embedded Systems',
        'Topic :: Software Development :: Debuggers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        # 'Programming Language :: Python :: 3.2',
        # 'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        # 'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6'
    ],
    keywords='map memory compiler debugger development embedded',
    packages=['mapography'],
    python_requires='>=2.7')
